/* Shared icon set — Font Awesome (free-solid) behind one stable API.
   <Icon name="check" />                              decorative (aria-hidden)
   <Icon name="bell" decorative={false} label="..." /> interactive
   <Icon name="circle" style={{ color: "#16a34a" }} />  status dots */

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faArrowLeft,
  faArrowRight,
  faArrowsRotate,
  faBell,
  faBolt,
  faBox,
  faBuilding,
  faCalendarDays,
  faCamera,
  faChartColumn,
  faCheck,
  faChevronDown,
  faCircle,
  faClipboardList,
  faClock,
  faCommentDots,
  faDownload,
  faEllipsisVertical,
  faEye,
  faFileLines,
  faFilter,
  faFlag,
  faFolder,
  faGear,
  faHammer,
  faHeart,
  faHelmetSafety,
  faImage,
  faInbox,
  faLightbulb,
  faListCheck,
  faLocationDot,
  faLock,
  faMagnifyingGlass,
  faMicrophone,
  faMobileScreen,
  faPaperPlane,
  faPen,
  faPlus,
  faPrint,
  faRightFromBracket,
  faRobot,
  faRocket,
  faShieldHalved,
  faTableCellsLarge,
  faTrash,
  faTriangleExclamation,
  faTruck,
  faUpload,
  faUser,
  faVideo,
  faWallet,
  faWandMagicSparkles,
  faWrench,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

export const ICONS = {
  dashboard: faTableCellsLarge,
  building: faBuilding,
  calendar: faCalendarDays,
  wrench: faWrench,
  eye: faEye,
  alert: faTriangleExclamation,
  siren: faTriangleExclamation,
  sparkles: faWandMagicSparkles,
  settings: faGear,
  logout: faRightFromBracket,
  bell: faBell,
  check: faCheck,
  chart: faChartColumn,
  wallet: faWallet,
  arrowRight: faArrowRight,
  arrowLeft: faArrowLeft,
  chevronDown: faChevronDown,
  package: faBox,
  rocket: faRocket,
  bot: faRobot,
  zap: faBolt,
  clipboard: faClipboardList,
  list: faListCheck,
  shield: faShieldHalved,
  helmet: faHelmetSafety,
  hammer: faHammer,
  chat: faCommentDots,
  user: faUser,
  mic: faMicrophone,
  send: faPaperPlane,
  bulb: faLightbulb,
  file: faFileLines,
  search: faMagnifyingGlass,
  plus: faPlus,
  trash: faTrash,
  xmark: faXmark,
  camera: faCamera,
  video: faVideo,
  upload: faUpload,
  rotate: faArrowsRotate,
  folder: faFolder,
  location: faLocationDot,
  image: faImage,
  truck: faTruck,
  clock: faClock,
  print: faPrint,
  inbox: faInbox,
  heart: faHeart,
  pen: faPen,
  phone: faMobileScreen,
  circle: faCircle,
  flag: faFlag,
  lock: faLock,
  filter: faFilter,
  download: faDownload,
  ellipsis: faEllipsisVertical,
};

export function Icon({ name, decorative = true, label, style, className }) {
  return (
    <FontAwesomeIcon
      icon={ICONS[name] || ICONS.dashboard}
      aria-hidden={decorative ? "true" : undefined}
      role={decorative ? undefined : "img"}
      aria-label={decorative ? undefined : label}
      focusable="false"
      style={style}
      className={className}
    />
  );
}
